### ISSUE TITLE
Check for unused fields in records

### ISSUE THREAD

**Issue by HernanRivasAcosta** [inaka/elvis#117]
Records can grow stale and end up with unused fields that only serve to add clutter and confuse programmers implying the code does some things or considers certain variables that it doesn't.

**Comment by paulo-ferraz-oliveira** [comment]
By "unused fields" do you mean "fields that aren't ever set"?

I see the following:
1. fields might be set in the context of one app. and read by another app., though they may also be set "by default",
2. fields might be read by an app. that is outside the context of compilation (so checking if they are read in that context is, indeed, not enough),
3. if a record is exported (e.g. via a function) it may be set by an external app. and then read.

I find this rule kind of hard to reason about, but probably with a proper list of requirements we'd be able to tackle it.

e.g. we could start by tackling records that aren't exposed outside of a module (thus excluding `.hrl`) - if they are opaque, they are supposedly easier to reason about, regarding this rule.

**Comment by elbrujohalcon** [comment]
There will be a solution for this… in a different project that I can't disclose much about… 🙄 … yet.
So, yeah… this ticket can be closed.

**Comment by paulo-ferraz-oliveira** [comment]
> There will be a solution for this… in a different project that I can't disclose much about… 🙄 … yet.
> So, yeah… this ticket can be closed.

Oh, the suspense... :D
