### ISSUE TITLE
Extending default configuration.

### ISSUE THREAD

**Issue by mpmiszczyk** [inaka/elvis#166]
We are using [github webhook](https://github.com/inaka/elvis#webhook).  And as far as I understand, only way to change some configuration is to create new `elvis.config` which consists "whole" config. What we would like to do is use the defautl one, with all the rules, and disable just one of them (or change options on it).

Coping default config is not something we would like to do.  Mainly due to fact, that we could not easily see which options are project specific, and we could loose some new rules (one would have to keep track of all new rules, and  update config accordingly). 

Is there a way to just extend default config? Add/remove rules, or just override rule options?

If not it would be a great feature.

**Comment by harenson** [comment]
Closed in https://github.com/inaka/elvis_core/pull/18
