### ISSUE TITLE
Standardize output and make it parseable

### ISSUE THREAD

**Issue by JonGretar** [inaka/elvis#169]
I was thinking of making a linter plugin for Atom using Elvis as the base like I have already done for Erlc.

But one of the things needed would be a more standardized output that can be more machine parseable. Most errors can be parsed as `"Line <LINE> <MESSAGE>"` but that is not a rule it seems.

What would really be wonderful is an optional parameter to the command line. Something like `[-p|--parseable]`. That would transform the output to something like `"<RULE_NAME>:<FILE>:<LINE>:(<COL>:) <MESSAGE>"`. Another possibility would be a JSON object for each error.

I'll be happy to produce a patch for this if we can find some output you like.

**Comment by define-null** [comment]
Probable https://github.com/inaka/elvis/issues/497 ?

**Comment by elbrujohalcon** [comment]
Yeah, @define-null … maybe related. I believe that if there is a way to use `output_format` for this, we should use it.

**Comment by elbrujohalcon** [comment]
Let's keep the discussion in #497 but let's also keep this issue open since it's a different format.

**Comment by paulo-ferraz-oliveira** [comment]
This is what the README states for `{output, parsable}`:

> The latter [`parsable`] could be use for the automated parsing and has a format very close to dialyzer in a form `FILE:LINE:RULE:MESSAGE`

Is this what this Issue is referring to?

**Comment by jfacorro** [comment]
@paulo-ferraz-oliveira Yes, inaka/elvis_core#106 implements exactly what is described in this issue.
