### ISSUE TITLE
Specify source file on the command line

### ISSUE THREAD

**Issue by JonGretar** [inaka/elvis#170]
Specifying a source file on the command line, to limit the lint to, instead of running on the whole project would be beneficial for writing linter plugins for editors.

**Comment by jfacorro** [comment]
@elbrujohalcon @JonGretar I think this is strongly related to #152.

**Comment by elbrujohalcon** [comment]
@jfacorro I agree

**Comment by elbrujohalcon** [comment]
@JonGretar have you already created a plugin for any editor? (I'm hoping emacs, since that's what @ttyerlsol is waiting for :)
