### ISSUE TITLE
file exceptions / global ignore (config)

### ISSUE THREAD

**Issue by andreineculau** [inaka/elvis#190]
I am generating a module, and I would like it to be excluded from elvis checks, although it's placed in `src` along the others.

PS: I might send a PR, but in case I forget..

**Comment by jfacorro** [comment]
A group based `ignore` option has been added in inaka/elvis_core#6.

**Comment by jfacorro** [comment]
@andreineculau @rymir I'm closing this issue based on the previous comment. If you find it doesn't meet your need please let us know and we can discuss it.

**Comment by andreineculau** [comment]
let's discuss it :)
