### ISSUE TITLE
Guys, please stop deleting/changing tags

### ISSUE THREAD

**Issue by essen** [inaka/elvis#198]
Posting here but this applies to many Inaka projects.

I am currently adding a test in erlang.mk to make sure all packages build. Some (many?) of the projects you submitted had the wrong tag to begin with, a project has been entirely removed (ebitly), but more importantly: some tags seem to have been removed or renamed. For example when elvis was added to erlang.mk the tag was explicitly set to 0.1.0-alpha. The tag is now gone and the 0.1.0 tag is more recent than the other one, suggesting it was renamed.

Please, never do this again. What you push to a public git repository, barring any legal obligation, should never change, otherwise tools and forks will break.

None of the projects from Inaka have worked so far, and all broken projects so far are from Inaka. I will update all project version to "master" to ensure it works. This may or may not be what you want.

Feel free to close. I just wanted to bring this issue to your attention.

**Comment by elbrujohalcon** [comment]
Thanks for the advice, @essen 
I'm sending an internal email now with this after closing the issue.
I'll be cc'ing you in it so we can discus this further there.

**Comment by essen** [comment]
Cool thanks for humoring me. :-)
