### ISSUE TITLE
Possible false positive?

### ISSUE THREAD

**Issue by technion** [inaka/elvis#236]
Hi,

I'm trying to resolve an issue I'm encountering with Elvis on this piece of code within a EUnit test.

```erlang
ip_results_to_json_test() ->
    ?assertEqual(ip_results_to_json([{{127, 0, 0, 253}, not_vulnerable}, {{127, 0, 0, 252}, not_vulnerable}]),
            <<"[{\"address\":\"127.0.0.253\",\"stat\":\"not_vulnerable\"},{\"address\":\"127.0.0.252\",\"stat\":\"not_vulnerable\"}]">>).
```

The last of those lines is line 39 of the code, producing this error:

```shell
# src/ipmangle.erl [FAIL]
  - operator_spaces
    - Missing space after "," on line 39
```

As far as I can see, that is binary data, and it shouldn't be considering those commas to be operators. Implementing those spaces changes the data the function is expecting.

If it helps, the complete codebase is here: https://github.com/technion/erlvulnscan

It's my first Erlang project so I could easily be missing something obvious :)

**Comment by jfacorro** [comment]
@technion This is definitely a false positive, so it is a bug in elvis. We will take a look at it as soon as possible. Thank you for reporting this.

**Comment by jfacorro** [comment]
Possibly related to #233

**Comment by jfacorro** [comment]
@technion This should be fixed in `master`. Sorry for the delay :stuck_out_tongue_closed_eyes:. Could you please confirm when you get the chance?

**Comment by technion** [comment]
No problems, tested and confirmed resolved.
