### ISSUE TITLE
The default for git_for_deps_erlang_mk should be https

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#238]
This goes hand in hand with inaka/erlang_guidelines#51

**Comment by jfacorro** [comment]
- [ ] Rename `git_for_deps_erlang_mk` to `protocol_for_deps_erlang_mk`.
- [ ] Create a function named `git_for_deps_erlang_mk` that calls `protocol_for_deps_erlang_mk`.
- [ ] Mark `git_for_deps_erlang_mk` as deprecated in the wiki everywhere it is mentioned.
- [ ] Update all config files replacing the old name for the new name.
