### ISSUE TITLE
Detect and enforce comma placement style

### ISSUE THREAD

**Issue by igaray** [inaka/elvis#276]
e.g. Trailing commas vs leading commas

``` erlang
{a, 
  [ 1, 
    2, 
    3
  ]
}.
```

vs

``` erlang
{a
, [ 1 
  , 2 
  , 3
  ]
}.
```

**Comment by elbrujohalcon** [comment]
Just a warning: you need to distinguish between commas in lists and tuples and commas separating expressions.
I'm pretty sure that will not be trivial.

**Comment by paulo-ferraz-oliveira** [comment]
I think `rebar3_format` addresses this issue, kind of, doesn't it?

**Comment by elbrujohalcon** [comment]
It does, indeed.

**Comment by jfacorro** [comment]
🎉  `rebar3_format` already supports comma first?

**Comment by elbrujohalcon** [comment]
No. It just supports _consistent comma placement_ :trollface:
