### ISSUE TITLE
Update for rebar3

### ISSUE THREAD

**Issue by igaray** [inaka/elvis#280]
The rule `protocol_for_deps_rebar` errors out with `function_clause` when trying to process rebar3 config files.

**Comment by Licenser** [comment]
I think this was closed by #294 , at least the function clause error

**Comment by waisbrot** [comment]
I'm not having any problems with my rebar3 configs, which include pulling dependencies from Hex.pm. I don't think Elvis looks at any other part of the file.

**Comment by igaray** [comment]
I built the latest elvis and still get the function clause error with the following config: 

```erlang
{deps, [
        cowboy,
        lager,
        png,
        {eper, {git, "https://github.com/massemanet/eper.git",{tag,"0.96.4"}}},
        {jiffy, {git, "https://github.com/davisp/jiffy.git"}},
        {worker_pool, {git, "https://github.com/inaka/worker_pool.git"} },
        {xref_runner, {git, "https://github.com/inaka/xref_runner.git",{tag,"0.2.2"}}}
        ]}.
```

**Comment by waisbrot** [comment]
I can reproduce this. `jiffy` and `worker_pool` are the two deps that are causing the problem.

A shorter version of your failing deps:

```
{deps, [
        {jiffy, {git, "https://github.com/davisp/jiffy.git"}}
        ]}.
```
