### ISSUE TITLE
Globally ignore autogenerated erlang module from review

### ISSUE THREAD

**Issue by rymir** [inaka/elvis#281]
I have some autogenerated protobuffs source code in my project and I would like to nicely ask elvis to globally ignore it, any suggestions?

**Comment by jfacorro** [comment]
@rymir Sadly, there's currently no good way of doing this other than playing around with the [`dirs`](https://github.com/inaka/elvis/blob/master/config/elvis.config#L6) and `filter` values in the `elvis.config` file.

I think it would be a nice optional feature though. It could be implemented by adding an `ignore_dirs` or  `ignore_filter` value to the configuration file.

**Comment by elbrujohalcon** [comment]
duplicated of #190
