### ISSUE TITLE
Make Elvis a third-party Erlang.mk plugin

### ISSUE THREAD

**Issue by essen** [inaka/elvis#289]
I would like to drop Elvis from the core Erlang.mk repository. I am currently documenting/testing plugins and came across a few third party things that should really be external plugins: Cowboy related templates, ErlyDTL and protobuffs compilation and Elvis.

Recently-ish I added support for external plugins, which can be loaded by using PLUGIN_DEP = elvis, for example. More info at https://github.com/ninenines/erlang.mk/blob/master/doc/src/guide/external_plugins.asciidoc

Would be great if you could try that. If it works, my work on the docs will amount to simply linking to this project's page rather than repeating everything.

**Comment by jfacorro** [comment]
@Euen @elbrujohalcon I would create a new repository `elvis.mk` like we did with [`hexer.mk`](https://github.com/inaka/hexer.mk).

**Comment by elbrujohalcon** [comment]
@jfacorro you mean like [this one](https://github.com/inaka/elvis.mk)? :trollface:
