### ISSUE TITLE
Reject use of export_all

### ISSUE THREAD

**Issue by kbaird** [inaka/elvis#290]
Keeping `export_all` in place after initial development work is typically considered a bad practice.

A rule that complains when that is still present in a file might be useful.

**Comment by igaray** [comment]
:+1:

**Comment by elbrujohalcon** [comment]
:+1: and can you add a similar issue in [the guidelines](http://github.com/inaka/erlang_guidelines), please?

**Comment by kbaird** [comment]
https://github.com/inaka/erlang_guidelines/pull/60, although it appears to have some errors from gadget/compiler and gadget/xref.

**Comment by bullno1** [comment]
Considering that conditionally `export_all` if `TEST` is defined is common practice:

```erlang
-ifdef(TEST).
-compile(export_all).
-endif.
```

The source needs to be compiled, not just parsed. Without access to compile flags like include path, defines... it would not be trivial to compile a source file. Besides, treating warning as error seems to catch this, is it still necessary to make this a rule?

**Comment by bullno1** [comment]
I guess, using a `-ifdef(TEST)` to conditionally `export_all` should be acceptable?

**Comment by elbrujohalcon** [comment]
@bullno1 you were correct somewhere else where you pointed out that the compiler itself can give you this same warning. Therefore, this rule should not be default and the implementation of this rule should be considered a very very low priority.
In any case, I wouldn't add any exception like that for `ifdef`, if you want to do that, just don't include this rule in your elvis.config or just ignore the module where you do that altogether.

**Comment by paulo-ferraz-oliveira** [comment]
> I guess, using a `-ifdef(TEST)` to conditionally `export_all` should be acceptable?

I've used it and find no issue with it, unless the consumer is being smart and deploying production code with TEST defined. :D

To build on what @elbrujohalcon commented, I find this rule won't bring relevant added value. Even more so since for a few Erlang/OTP versions already, `warn_export_all` is on by default, so you explicitly have to turn the warning off.

**Comment by elbrujohalcon** [comment]
Closing this ticket.
