### ISSUE TITLE
Elvis github integration fails when renaming files

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#291]
If, in a PR, a file is just renamed (i.e. not modified, just `mv x y`), it includes no `patch` attribute in its JSON description. Therefore this fails with a `function_clause` error:
```erlang
-module(elvis_webhook).

…

file_info(Cred, Repo,
          #{<<"filename">> := Filename,
            <<"raw_url">> := RawUrl,
            <<"patch">> := Patch}) ->
```

**Comment by harenson** [comment]
This is not an `elvis` issue but a [`gadget issue`](https://github.com/inaka/gadget/issues/137) and it is already [`fixed`](https://github.com/inaka/gadget/pull/151).

Also `elvis_webhook:file_info/3` return the information for every file in the `GithubFiles` parameter passed to `elvis_webhook:handle_pull_request/3` and everyone of those files does contain a `<<"patch">>` key.
