### ISSUE TITLE
Uncorrect detecting rule missing space after ","

### ISSUE THREAD

**Issue by platinumthinker** [inaka/elvis#296]
Retry in code:
```
re:run(Name, "^.{1,20}$", [unicode]);
```
But work in this case:
```
RegExp = "^.{1,20}$",
re:run(Name, RegExp, [unicode]);
```

**Comment by jfacorro** [comment]
@harenson I think you verified this after closing #319 and it is now working correctly?

**Comment by harenson** [comment]
@jfacorro Yeah, there is an open PR for this test at https://github.com/inaka/elvis_core/pull/22

This was fixed in https://github.com/inaka/elvis_core/pull/20
