### ISSUE TITLE
Uncorrect detecting length of unicode strings

### ISSUE THREAD

**Issue by platinumthinker** [inaka/elvis#297]
Except in code:
```
test() ->
    A = "▁▃▅▆㊅㊆㊍㊎▆▄▂▁▁▃▅▆㊅㊆㊍㊎▆▄▂▁▁▃▅▆㊅㊆㊍㊎▆▄▂▁"
    io:format("~p", [A]).
```

**Comment by jfacorro** [comment]
Hi, @platinumthinker, thanks for reporting this issue! It has been recently fixed in this PR #293. There is no release that includes this fix yet though.

**Comment by platinumthinker** [comment]
I use erlang 17, and build elvis from git repo (hash 1b0ec74667a2c6ed76a207e9abc9902038cd47a5).
This bug is repeating

**Comment by platinumthinker** [comment]
@jfacorro  I use elvis from git repo (hash c0453e85614b7793852de0377070d41776a8d625)
and erlang-17. This bug repeating
