### ISSUE TITLE
Rule idea: application name as module prefix

### ISSUE THREAD

**Issue by fredrikelinder** [inaka/elvis#304]
Hello

Since all application share the same module namespace, it would be real neat to add an option to the module name rule to require all module names to be prefixed by the application name.
- For single application repositories one could just add it to the `regex`.
- For multi application repositories with a single elvis configuration that would be insufficient.

Perhaps like this

```
{
 elvis_style,
 module_naming_convention,
 #{regex => "^([a-z][a-z0-9]*_?)*(_SUITE)?$",
   ignore => [],
   prefix => application}
}
```

Makes sense?

**Comment by jfacorro** [comment]
@fredrikelinder This is possible by just modifying the regex. What advantage would the `prefix` option bring vs. modifying the `regex` option?

**Comment by jfacorro** [comment]
For multiple application repositories with a single `elvis.config` file a possible regular expression could be: `^(app1|app2|app3)_([a-z][a-z0-9]*_?)*(_SUITE)?$`.

**Comment by fredrikelinder** [comment]
That would allow `app1` as prefix for `app2` files

**Comment by paulo-ferraz-oliveira** [comment]
> That would allow `app1` as prefix for `app2` files, which isn't desirable.
> 
> In other words: without the `prefix` option there is no way to warn about files in `app2` application being named `app1_*` (using your example regex).

`elvis.config` supports multiple config. maps, each with its own `dirs` option.

Stuff like
```erlang
[{elvis, [{config, [
    #{ dirs => ["apps/app1"],
       filter => "*.erl",
       ruleset => erl_files,
       rules => [{elvis_style, module_naming_convention,
                  #{ regex => ["^app1_([a-z][a-z0-9]*_?)*(_SUITE)?$"] }}] }, 
    #{ dirs => ["apps/app2"],
       filter => "*.erl",
       ruleset => erl_files,
       rules => [{elvis_style, module_naming_convention,
                  #{ regex => ["^app2_([a-z][a-z0-9]*_?)*(_SUITE)?$"] }}] }
]}]}].
```
is possible and solves your particular issue.

**Comment by elbrujohalcon** [comment]
exactly!
