### ISSUE TITLE
There is not elvis:webhook/1 function anymore so please update the documentation

### ISSUE THREAD

**Issue by harenson** [inaka/elvis#322]
Outdated documentation references `elvis:webhook/1`: https://github.com/inaka/elvis#running-the-webhook-on-your-servers

**Comment by JohanVikman** [comment]
How do you want this fixed? Is the webhook functionality removed altogether?

**Comment by jfacorro** [comment]
@JohanVikman The [webhook](https://github.com/inaka/elvis/blob/master/src/elvis_webhook.erl) functionality is there, but it seems the service is no longer working http://elvis.inakalabs.com/.

**Comment by harenson** [comment]
@JohanVikman @jfacorro Yes, the functionality is still there, but the function `webhook` with arity `1` within the `elvis` module doesn't exist [anymore](https://github.com/inaka/elvis/commit/974d9df871089ee15b9896ce13eebaf7523adb63). The aim of this issue is to update the documentation by pointing to the new implementation of this functionality which if I recall correctly would be calling [elvis_webhook:event/1](https://github.com/inaka/elvis/blob/master/src/elvis_webhook.erl#L12) instead.

**Comment by JohanVikman** [comment]
Created a PR
