### ISSUE TITLE
can I exclude files from the check?

### ISSUE THREAD

**Issue by hachreak** [inaka/elvis#356]
I started to use this [rebar3 plugin](https://github.com/project-fifo/rebar3_lint) to run `lint` check on my project [mongoql](https://github.com/hachreak/mongoql).
I'm using yecc and leex and they generate some `.erl` files on which I have no control.
I have many warnings on them.
Exists the possibility to exclude them from the check?

**Comment by harenson** [comment]
Yes, you can exclude any module(s) by setting the **ignore** parameter in the rule you want to skip, e.g:

```erlang
{elvis_style, no_debug_call, #{ignore => [elvis, elvis_utils]}}
```

In the previous tuple we are telling elvis to **ignore** *elvis* and *elvis_utils* modules when running `no_debug_call` check.

**Comment by harenson** [comment]
In the last comment I show you how to ignore one or many files for a given check. If what you want is just to ignore a group of checks for one or more files, you can also do that by setting the **ignore** group level option for the group you want to skip, e.g:

```erlang
#{dirs => ["src"],
  filter => "*.erl",
  ruleset => erl_files,
  ignore => [module1, module4]
 }
```

In the last example, none of the checks for [erl_files](https://github.com/inaka/elvis_core/blob/master/src/elvis_rulesets.erl#L6-L34) would be applied to `module1.erl` and `module4.erl` files.

Also, we have created an [issue](https://github.com/inaka/elvis/issues/357) for adding documentation about that group level option.

**Comment by hachreak** [comment]
Thank you very much for the help!
This is a very nice tool! I already added it to all my projects... XD
Do you know if there is some integration of `elvis` with [vim-erlang](https://github.com/vim-erlang) tools? (If no, if there are plans to integrate)

**Comment by elbrujohalcon** [comment]
@hachreak there is no integration with vim that I know of and no plans for it around here… but you're very much welcome to add it yourself :)
