### ISSUE TITLE
nesting_level

### ISSUE THREAD

**Issue by andreineculau** [inaka/elvis#361]
I am somewhat surprised by the semantics of the `nesting_level` rule.

Judging by https://github.com/inaka/elvis_core/blob/0fa177d5644ae0cb14883264d4296e62873306cd/src/elvis_code.erl#L149
you say that code under a function is already nested (level 1), meaning that with the default of 3

``` erlang
fun(A, B, C) ->
  ok, % level 1 %%% huh, ok is nested in a fun?!
  case A of
    true ->
      ok, % level 2
      case B of
        true ->
          ok, % level 3
          case C of
            true ->
              error; % level 4
```

By my semantics, error is nested under 3 cases (level 3), not under 3 cases and 1 fun (level 4).

**Comment by elbrujohalcon** [comment]
@andreineculau why don't you consider `fun` a nesting construct?

It has clauses, like the others nesting constructs (i.e. `try`, `if`, `case`, `receive`, etc.). The code in those clause bodies is typically _indented_ (even in your example).

I don't see why would exclude funs from the list of nesting constructs.

**Comment by andreineculau** [comment]
Indentation has nothing to do with nesting: `fun(A) -> case A of true -> nested; false -> nested end end.` :)

I'm not excluding all funs e.g. inlined, just the top-level ones in a module. For instance the main function of an escript - I would never ever think of it as "nested level 1".

But if you think it's correct, then it's correct (at least in the elvis world :) ).
Thanks!

**Comment by elbrujohalcon** [comment]
Ohhh! I see your point. I mixed _nesting_ with _indenting_. My bad.

And I see now that you were not talking about `fun`s, you were talking about *functions*.

I don't have a strong opinion there. Let's open this up for discussion. I'll turn this issue into a question and let people have their voice about it.

**Comment by sstrigler** [comment]
Since you're asking, I was also surprised when I learned about that behavior. That way there is no way for code to not be nested.

**Comment by andreineculau** [comment]
On Fri, Mar 18, 2016 at 2:27 PM, Stefan Strigler <notifications@github.com>
wrote:

> That way there is no way for code to not be nested.


bingo!


-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by erszcz** [comment]
The only practical difference is the number we put in as the default (or per project) setting. From some experience in Escalus, I also think 4 might be better than 3 (quite clean code raises warnings with the default level 3):

```erlang
ensure_table_present(T) ->
    case ets:info(T) of
        undefined ->
            P = spawn(fun() -> ets:new(T, [named_table, public]),
                               receive bye -> ok end end),
            erlang:register(T, P);
        _nasty_table_is_there_well_run_with_it -> ok
    end.
```

IMO this is OK, but for Gadget with level set to 3, it's "too nested" already.

**Comment by elbrujohalcon** [comment]
@erszcz If I were to review that code, I would totally ask you to split that code in two functions. Something like…

```erlang
ensure_table_present(T) ->
    case ets:info(T) of
        undefined -> create_table(T);
        _nasty_table_is_there_well_run_with_it -> ok
    end.

create_table(T) ->
  P =
    spawn(
      fun() ->
        ets:new(T, [named_table, public]),
        receive bye -> ok end
      end),
  erlang:register(T, P).
```

But it's ok, if everybody considers the main function as no-indent (which I'm finding reasonable by this moment), I might _overlook_ the fact that I should reduce the default value and let it be 3 so you can get away with it without adding an elvis.config to your repo ;)

**Comment by paulo-ferraz-oliveira** [comment]
Is this still a valid concern?

I could propose an `elvis.config` option like `{base_nesting_level, 0}`, but would that make so much of a difference, since that value can already be tweaked? Is it better to have a default of `4` instead of `3`?

I personally start to find code "complicated" after 2, but it's a question of habit, I guess.

Here's what inspired me to reduce nesting levels in the past: [YouTube: Writing Quality Code in Erlang, by Garrett Smith](https://www.youtube.com/watch?v=CQyt9Vlkbis).

**Comment by elbrujohalcon** [comment]
At this point in time I would just move the default to `4` and be done with it.

**Comment by paulo-ferraz-oliveira** [comment]
I did just that a bit more. Maybe the issue is ready to be closed now.
