### ISSUE TITLE
How to implement my own rules?

### ISSUE THREAD

**Issue by fenollp** [inaka/elvis#363]
I saw https://github.com/inaka/elvis#user-defined-rules
How do I write my own rules? I can't seem to find even Elvis' own default rules

**Comment by elbrujohalcon** [comment]
You can find examples [here](https://github.com/inaka/elvis_core/blob/master/src/elvis_style.erl) and [here](https://github.com/inaka/elvis_core/blob/master/src/elvis_project.erl)
