### ISSUE TITLE
Properly document elvis.config

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#380]
Add samples and proper descriptions explaining what you can do and how to do it with that file.

**Comment by JohanVikman** [comment]
Where do you want this? In the README.md?

**Comment by elbrujohalcon** [comment]
Hi @JohanVikman !
README.md would be great but, if it's too limited, maybe you can write a wiki page and link to it from the README.md file.

**Comment by elbrujohalcon** [comment]
As a matter of fact, the wiki (from this repo and elvis_core as well) is in desperate need for some clean-up/update.

**Comment by JohanVikman** [comment]
Please take a look at my pr @elbrujohalcon . Is it ok?

**Comment by paulo-ferraz-oliveira** [comment]
I believe this might be related to https://github.com/inaka/elvis/issues/438, but this issue, itself, is already dealt with (though still open), right?

**Comment by elbrujohalcon** [comment]
Yeah. I'm closing it.
