### ISSUE TITLE
Crash reviewing rebar.config deps with pkg_name

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#395]
When your rebar.config contains things like…

``` erlang
{deps, [{iso8601, "1.1.2", {pkg, inaka_iso8601}}]}.
```

…elvis reports the following error…

``` erlang
# rebar.config [FAIL]
Error: 'badarg' while applying rule 'protocol_for_deps_rebar'.
```

**Comment by paulo-ferraz-oliveira** [comment]
This also happens for raw dependencies such as `{raw, {git, "https://github.com/non_ot_project.git", {tag, "0.0.1"}}}`

**Comment by paulo-ferraz-oliveira** [comment]
I cannot replicate this. Shall the issue be closed?
