### ISSUE TITLE
Check fails on eunit tests

### ISSUE THREAD

**Issue by bartekgorny** [inaka/elvis#403]
When checking a test module using eunit's ?assertEqual macros, elvis fails because of naming convention violation. This is because stock eunit.hrl defines those macros using variable names like __X, macros are expanded etc. We need at least a workaround, otherwise we'd have to choose between elvis and eunit which would be a difficult choice indeed.

**Comment by elbrujohalcon** [comment]
@bartekgorny you can configure that rule… or just disable it for the test modules.

**Comment by jfacorro** [comment]
@elbrujohalcon The [`macro_names`](https://github.com/inaka/elvis_core/blob/master/src/elvis_style.erl#L222) rule doesn't seem to have any configurable option 😞 .

**Comment by harenson** [comment]
@jfacorro I think the he is getting an error bout `variable_naming_convention` not about `macro_names`. If that is the case @bartekgorny you can override the rule's configuration by passing a map containing a `regex` key with a proper regex to allow underscores at the beginning of variable names or ignore that file using the `ignore` configuration key.

If you want to accept underscores at the beginning of the variable names by overriding the variable_naming_convention rule use something like this:

```erlang
[
 {
   elvis,
   [
    {config,
     [#{dirs => ["src"],
        filter => "*.erl",
        rules => [{elvis_style,
                   variable_naming_convention,
                   #{ regex => "^([_A-Z][0-9a-zA-Z]*)$" }}],
        ruleset => erl_files
       } %,
       % ...
     ]
    }
   ]
 }
].
```

**Comment by elbrujohalcon** [comment]
@harenson: he's having issues with [macro_names](https://github.com/inaka/elvis_core/blob/master/src/elvis_style.erl#L767) and @jfacorro is right: the `Regex` is [hardcoded](https://github.com/inaka/elvis_core/blob/master/src/elvis_style.erl#L768).

A PR with a `regex` parameter for this rule, like the one for `variable_naming_convention` would be much appreciated.

**Comment by bartekgorny** [comment]
The message is about variable naming:
```
- variable_naming_convention
    - The variable "_V" on line 90 does not respect the format defined by the regular expression '"^([A-Z][0-9a-zA-Z]*)$"'.
```
It comes from a macro because `?assertEqual` defined in `eunit.hrl` does things like:
```
-define(assertEqual(Expect, Expr),
	begin
	((fun (__X) ->
	    case (Expr) of
		__X -> ok;
```
So, yes, seems I can solve it by crafting a regexp allowing double underscore at the beginning of a variable name. Thanks a lot!
