### ISSUE TITLE
Style rules for the seqbind transform

### ISSUE THREAD

**Issue by gnuvince** [inaka/elvis#413]
The seqbind parser transform allows Erlang code to reuse the "same" variable name multiple times:

```erlang
X@ = 10,
X@ = X@ + 1.
```

Though useful sometimes, its usage is typically a code smell.  I have created two new style rules (https://github.com/gnuvince/elvis_core/pull/1):

- The `no_seqbind` rule warns when a module declares its intention to use seqbind (`-compile({parse_transform, seqbind}).`);
- The `no_useless_seqbind` rule warns when a module has activates the seqbind transform, yet never makes any use of it (i.e., no `Var@` names anywhere in the module).

**Comment by elbrujohalcon** [comment]
@gnuvince just curious: where do you get that parse_transform from?
I haven't seen anything like that in my ~10 years as an Erlanger. 😱

**Comment by gnuvince** [comment]
@elbrujohalcon It's an option for the compiler: http://erlang.org/doc/man/compile.html (scroll down a few screenfuls).

**Comment by elbrujohalcon** [comment]
I know what parse_transform is ;). I was asking where did you get this one (seqbind) in particular.

**Comment by gnuvince** [comment]
Oops, misread, sorry! Here's their Github repo: https://github.com/spawngrid/seqbind

**Comment by elbrujohalcon** [comment]
Thanks. Please send a PR over with your rules, then :)

**Comment by gnuvince** [comment]
PR submitted: https://github.com/inaka/elvis_core/pull/67

The gadget/compiler check failed, but I'm not sure what the problem is.

**Comment by DBoroujerdi** [comment]
@gnuvince I commented on issue #418  about failed tests, but I hadn't seen this issue. It's related to this seqbind merge and could be the cause of the gadget/compiler check you mention.
