### ISSUE TITLE
Increase signal and reduce noise?

### ISSUE THREAD

**Issue by Nyco** [inaka/elvis#422]
# Problem
One "message" from elvis contains very few information (yet useful).

# Consequences
At each PR, we have plenty of (too many) little messages in the comments as well as notifications (on HipChat or whatever "integration").

# (probable?) Solution
It may be nice to regroup elvis "messages" per PR.

# Benefit
We just need to treat one unique elvis "message".

**Comment by elbrujohalcon** [comment]
Yes, elvis should be using the new review functionality on github. But this is mostly an issue for elvis-server (a private inaka repo), not this one ;)
