### ISSUE TITLE
elvis.config file documentation

### ISSUE THREAD

**Issue by ferigis** [inaka/elvis#437]
- Create an appropriate documentation for elvis.config file.
- Include an example about how to exclude some given modules from checks (something like [issue#356](https://github.com/inaka/elvis/issues/356) response)

**Comment by zsoci** [comment]
Please note when we can use wildcards in the file name rules. Examples would also be easier with wildcarding.

**Comment by elbrujohalcon** [comment]
Duplicate of #380
