### ISSUE TITLE
Create elvis.config.sample file

### ISSUE THREAD

**Issue by ferigis** [inaka/elvis#438]
with all the available fields. Related to [#437]

**Comment by paulo-ferraz-oliveira** [comment]
Is the [Rules wiki](https://github.com/inaka/elvis_core/wiki/Rules) enough for this? Or should we consider a different location for this file? I don't mind tackling this issue. I might even learn a few new things about `elvis`.

**Comment by elbrujohalcon** [comment]
We should add something like this to that wiki to solve the issue…

```erlang
[
 {
   elvis,
   [
    {config,
     [#{dirs => ["src"],
        filter => "*.erl",
        ruleset => erl_files
      },
      #{dirs => ["test"],
        filter => "*.erl",
        ruleset => erl_files
      },
      #{dirs => ["."],
        filter => "elvis.config",
        ruleset => elvis_config
      }
     ]
    }
   ]
 }
].
```

**Comment by elbrujohalcon** [comment]
with all possible entries (i.e. one for `rebar.confg`, one for `Makefile`, I guess…)

**Comment by paulo-ferraz-oliveira** [comment]
I added the example `elvis.config` section here: https://github.com/inaka/elvis_core/wiki/Rules#example-elvisconfig. I'm going to review the rules now.

**Comment by elbrujohalcon** [comment]
Excellent!!
