### ISSUE TITLE
Add `--verbose` flag, obey rule of silence of it's not passed

### ISSUE THREAD

**Issue by srenatus** [inaka/elvis#447]
Hey there.

I'd like to work on a small PR that makes`elvis rock` _output nothing_ (but exit 0) if there's no violation found, and _output the rule violations only_ if there are any.

Executing `elvis --verbose rock` would then make elvis behave like it does *today*

I expect that this proposal needs some discussion, and I could be convinced that a `--quiet` flag would be preferable (to not change the default). However, my favourite behaviour would be no-problem-no-output.

Any thoughts?

**Comment by elbrujohalcon** [comment]
I like your original idea, as long as, if there are warnings they're printed out as they're today.

**Comment by srenatus** [comment]
😃 Yay!

I've noticed that there already is a `no_output` flag in elvis_core, but it's not set by elvis. However, it's suppressing _all output_, which isn't what we'd want here.

**Comment by srenatus** [comment]
I'd assumed that #448's "Fixes..." comment would close this automatically... anyhow, thanks for merging those PRs, I'm looking forward to the next elvis release 😉
