### ISSUE TITLE
Elvis complains about dynamic function call in behaviour module

### ISSUE THREAD

**Issue by kzemek** [inaka/elvis#467]
The [callback is defined](https://github.com/esl/MongooseIM/blob/f99dfb3eb3d24bd0f68ca84fba6b1c848a7718f4/apps/ejabberd/src/event_pusher/mod_event_pusher_http_notification.erl#L17) in the module, but [Elvis complains about dynamic function call](https://github.com/esl/MongooseIM/pull/1414#discussion_r129545885) on a [line in the same module](https://github.com/esl/MongooseIM/blob/f99dfb3eb3d24bd0f68ca84fba6b1c848a7718f4/apps/ejabberd/src/event_pusher/mod_event_pusher_http_notification.erl#L42).

**Comment by elbrujohalcon** [comment]
I could isolate the issue.

This code generates no warnings:

```erlang
-module(x).
%-include("x.hrl").
-callback x() -> _.
x(X) -> X:x().
```

This code generates warnings:

```erlang
-module(x).
-include("x.hrl").
-callback x() -> _.
x(X) -> X:x().
```

This code generates no warnings either:

```erlang
-module(x).
-author("x.hrl").
-callback x() -> _.
x(X) -> X:x().
```

**Comment by elbrujohalcon** [comment]
Digging deeper, it looks like [aleppo](http://github.com/inaka/aleppo) is misunderstanding include attributes.

```erlang
1> MinContent = "-module(x).\n-include(\"x.hrl\").",
{ok, MinTokens, _} = erl_scan:string(MinContent, {1,1}, [text]),
rp({MinTokens, aleppo:process_tokens(MinTokens)}).
{[{'-',[{text,"-"},{location,{1,1}}]},
  {atom,[{text,"module"},{location,{1,2}}],module},
  {'(',[{text,"("},{location,{1,8}}]},
  {atom,[{text,"x"},{location,{1,9}}],x},
  {')',[{text,")"},{location,{1,10}}]},
  {dot,[{text,".\n"},{location,{1,11}}]},
  {'-',[{text,"-"},{location,{2,1}}]},
  {atom,[{text,"include"},{location,{2,2}}],include},
  {'(',[{text,"("},{location,{2,9}}]},
  {string,[{text,"\"x.hrl\""},{location,{2,10}}],"x.hrl"},
  {')',[{text,")"},{location,{2,17}}]},
  {dot,[{text,"."},{location,{2,18}}]}],
 {ok,[{'-',[{location,{1,1}},{text,"-"},{location,{1,1}}]},
      {atom,[{location,{1,2}},{text,"module"},{location,{1,2}}],
            module},
      {'(',[{location,{1,8}},{text,"("},{location,{1,8}}]},
      {atom,[{location,{1,9}},{text,"x"},{location,{1,9}}],x},
      {')',[{location,{1,10}},{text,")"},{location,{1,10}}]},
      {dot,[{location,{1,11}},{text,".\n"},{location,{1,11}}]},
      {string,[{location,{2,10}},
               {text,"\"x.hrl\""},
               {location,{2,10}}],
              "x.hrl"},
      {eof,0}]}}
ok
```

As you can see… aleppo is interpreting `-include("x.hrl").` as just…

```erlang
      {string,[{location,{2,10}},
               {text,"\"x.hrl\""},
               {location,{2,10}}],
              "x.hrl"},
```

…as if it was just `"x.hrl"`, i.e. the string floating around in the module.

**Comment by elbrujohalcon** [comment]
This is related to #468 since, as stated in inaka/aleppo#45, it can be _fixed_ by providing a proper list of include folders to `ktn_code:parse_tree`.

**Comment by harenson** [comment]
@kzemek in the meantime you could use elvis_core@0.3.9 and set proper `include_dirs` value so elvis can send it to aleppo.
