### ISSUE TITLE
Misuse of options

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#468]
When `elvis_file` calls `ktn_code:parse_tree/2` in [`resolve_parse_tree/3`](https://github.com/inaka/elvis_core/blob/master/src/elvis_file.erl#L112-L115), it uses a `map()` (actually it's elvis' configuration) as the first argument in the call:

```erlang
-spec resolve_parse_tree(map(), string(), binary()) ->
    undefined | ktn_code:tree_node().
resolve_parse_tree(Config, ".erl", Content) ->
    ktn_code:parse_tree(Config, Content);
```

But, `ktn_code:parse_tree/2` expects a `[string()]` in the first argument of [`parse_tree/2`](
https://github.com/inaka/katana-code/blob/master/src/ktn_code.erl#L95). What `ktn_code` expects is actually a list of include folders to pass in the options to `aleppo`:

```erlang
-spec parse_tree([string()], string() | binary()) -> tree_node().
parse_tree(IncludeDirs, Source) ->
    SourceStr = to_str(Source),
    ScanOpts = [text, return_comments],
    {ok, Tokens, _} = erl_scan:string(SourceStr, {1, 1}, ScanOpts),
    Options = [{include, IncludeDirs}],
    {ok, NewTokens} = aleppo:process_tokens(Tokens, Options),
```

**Comment by elbrujohalcon** [comment]
We should probably be fine by just using `ktn_code:parse_tree/1` instead of `ktn_code:parse_tree/2`

**Comment by harenson** [comment]
Fixed in https://github.com/inaka/elvis_core/pull/93
