### ISSUE TITLE
operator_spaces handles +,- and / signs as operator in cases where it is not an operator

### ISSUE THREAD

**Issue by f3c0** [inaka/elvis#483]
I tried to force `+`, `-` and `/` operators with spaces before and after.
Unexpected behaviour: 
 - all the signed numbers became invalid format
 - function references like function_name/2 have missing space message too

I've made a test repo for the bug: https://github.com/f3c0/elvis_test.git

```
$ git clone https://github.com/f3c0/elvis_test.git .
$ git checkout  test_operators_plus_minus_slash

$ elvis --version
   ______     _   
  / __/ /  __(_)__
 / _// / |/ / (_-<
/___/_/|___/_/___/
Version: 0.4.1
Elvis Core Version: 0.3.9

$ elvis rock
# src/elvis_test.erl [FAIL]
  - operator_spaces
    - Missing space right "/" on line 3
    - Missing space left "/" on line 3
    - Missing space right "-" on line 9
    - Missing space right "+" on line 11

```

**Comment by elbrujohalcon** [comment]
You're right, this is a bug.

**Comment by f3c0** [comment]
I have a very similar problem with `/` sign. 
Elvis handles it in the functions references like `function_name/2` as slash operator.
Should I open as separated bug, or just amend this?

**Comment by elbrujohalcon** [comment]
We should solve them both together, so I would say _just amend this one_

**Comment by f3c0** [comment]
Thanks, I've just updated the original report
