### ISSUE TITLE
Would you be interested in a Common Caveats rule?

### ISSUE THREAD

**Issue by adrianroe** [inaka/elvis#484]
A number of the common caveats listed in http://erlang.org/doc/efficiency_guide/commoncaveats.html could easily be picked up by Elvis.  I have a local elvis_core that adds a common_caveats rule.

The code is essentially identical to no_debug_calls, so I made a common function (no_call) that they both call - just with different configs.  I suspect it would be worth exposing no_call as a generic rule as well (with a default list of functions that is empty) to make it trivial for users to add "warn if anyone calls X/1, Y/2 or Z/3"...)

The common caveats themselves would include calls to timer:send_after / timer:send_interval, as well as erlang:size

**Comment by elbrujohalcon** [comment]
Hi @adrianroe ! Yeah! Please send a PR with that rule and we can review it together :)

**Comment by elbrujohalcon** [comment]
I also agree that `no_call` as a rule on its own makes sense.

**Comment by adrianroe** [comment]
Excellent - I'll work on a PR tonight

**Comment by adrianroe** [comment]
Pull request sent

**Comment by adrianroe** [comment]
WIKI page updated with the new rules
