### ISSUE TITLE
Outdated Docs

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#489]
We still have README.md and other places with references to the defunct elvis.inakalabs.com website.
We are also lacking some documentation that was there. For instance, a proper doc on all the things you can do in elvis.config files.

**Comment by jfacorro** [comment]
@elbrujohalcon What docs did we have that we lost from elvis.inakalabs.com?

**Comment by elbrujohalcon** [comment]
This is the best I could find, @jfacorro … check `config.dtl` in that zip file.
[templates.zip](https://github.com/inaka/elvis/files/3891618/templates.zip)

**Comment by elbrujohalcon** [comment]
[Here it is!!](http://web.archive.org/web/20160108010925/http://elvis.inakalabs.com/config)
🙏 All praise to the **Internet Archive WayBack Machine!!!** 🙏

**Comment by paulo-ferraz-oliveira** [comment]
Milestone removed, since 0.5.0 is in the past.
