### ISSUE TITLE
Possible problems with state_record_and_type validation

### ISSUE THREAD

**Issue by tothlac** [inaka/elvis#490]
Hi,

I'm using 088b7ac094678587b45ab2a97e751db6a0c37d44 (HEAD -> master, tag: 0.4.2

I have this in a module:

```
-module(example).
-behavior(gen_server).

-include("example.hrl").

-record(state, {
          oyveyh
}).

-type(state() :: #state{}).

-export([ start_link/0
        , init/1
        , handle_info/2
        , handle_call/3
        , handle_cast/2
        , terminate/2
        ]).

start_link() ->
  gen_server:start_link({local, ?MODULE}, ?MODULE, [], [{timeout, 3000}]).

init(_Args) ->
  {ok, #state{}}.

terminate(_, #state{} = _OS) ->
  ok.

handle_call(_Request, _From, State) ->
  {noreply, State}.

handle_cast({_Request, _From}, State) ->
  {noreply, State}.

handle_info(connect, OS) ->
  {noreply, OS}.

```

I got:

```
tothlac:proba elvis rock
# src/example.erl [FAIL]
  - state_record_and_type
    - This module implements an OTP behavior but is missing a 'state' record.
```

That's because elvis_style:is_otp_module/1 does not even check the behaviour attribute, it only checks behavior, which is possibly a bug. 
So it will work with -behaviour(gen_server), but in this case the check is not even called.
```
is_otp_module(Root) ->
    OtpSet = sets:from_list([gen_server,
                             gen_event,
                             gen_fsm,
                             supervisor_bridge
                            ]),
    IsBehaviorAttr = fun(Node) -> behavior == ktn_code:type(Node) end,

```

Then in state_record_and_type/4 it goes back to the {false, Other} clause, since has_state_record/1 returned false (has_state_type/1 returned true):
```
            case {has_state_record(Root), has_state_type(Root)} of
                {true, true} -> [];
                {false, Other} ->
                    Msg = ?STATE_RECORD_MISSING_MSG,
                    Result = elvis_result:new(item, Msg, [], 1),

```

I have this problem only if example.hrl is included, and only if example.hrl is not in the include folder but in src. If I move it to include or if I delete the include attr it works.
It also works if add
```
-record_attr(state).
```

Possible problems:
- the check is not called with -behaviour(gen_server). As far as I know OTP allows behaviour and behavior attributes.
- including a hrl from the src folder deletes record_attr hence I got the error.

**Comment by aboroska** [comment]
The following PR on aleppo fixes this: https://github.com/inaka/aleppo/pull/55
