### ISSUE TITLE
[Q] Ignore existing issues, without ignoring whole modules.

### ISSUE THREAD

**Issue by define-null** [inaka/elvis#497]
So there is project with a large code base, that has collected some bad code smells, which we would like to tackle. And with Elvis, as with Dialyzer it's impossible to fix everything at one go, you need to gradually polish off, and clean the code. The problem is, that currently it seems, the only way to ignore certain problems is to add module name to the ignore section of the rule. That could work for relatively small modules, but for large once if could become a real pain.
When it comes to dialyzer the common practice it seems - to create a dializer.ignore file with the warnings, that currently exist in the project, and gradually remove one line by one in the eventual phashion.

Before introducing any PRs, I'd like to reach out and get some opinion about similar approach for Elvis. Potentially to have a format mode, where elvis would print filename, line, and the error that it encounter. For rules like god modules the line could be equal to 1 or 0 for instance, just to indicate the problem.

What do you think of such an approach? Just to be clear, I want to generate output close to https://github.com/basho/riak/blob/develop/dialyzer.ignore-warnings

**Comment by elbrujohalcon** [comment]
We do have an `{output_format, …}` param that you can add to elvis.config
Is there any way to implement this change by extending the list of acceptable values for it?

**Comment by define-null** [comment]
Yes sure, I will update the PR to use new value in output_format instead

**Comment by paulo-ferraz-oliveira** [comment]
The linked PR is merged. Should this task be closed?

**Comment by elbrujohalcon** [comment]
Yes
