### ISSUE TITLE
FUNCTION_NAME macro treated as variable

### ISSUE THREAD

**Issue by hauleth** [inaka/elvis#505]
I am trying to write [Mix task for Elvis](https://github.com/haulet/mix_elvis) unfortunately when [some macro tries to use other macro twice](https://github.com/hauleth/mix_elvis/blob/3ac7e3f27b518ff46114ccb240e69c2a6da46571/test/fixtures/macros/include/test.hrl) it do not expand them and it results in treating `FUNCTION_NAME` as variable instead of macro, which in the end makes `variable_naming_convention` fails.

**Comment by aboroska** [comment]
I had the same issue. (embedded macros) The quick workaround was to add the following style rule to my `elvis.config`

    rules => [
      {elvis_style, variable_naming_convention,
                      #{regex => "^_?([_A-Z][0-9a-zA-Z]*)$|^FUNCTION_NAME$"}}
    ]

**Comment by hauleth** [comment]
@aboroska this isn't the only macro that would fail. TBH I think that any predefined macro will also fail as `FUNCTION_ARITY` also fires the error.

**Comment by hauleth** [comment]
Ok, it fails with `rebar3 lint` as well. I cannot find any solution, only workarounds.

**Comment by jfacorro** [comment]
There's a new version of elvis_core that should solve this issue and be able to detect macros, regardless of their names and usage.

**Comment by hauleth** [comment]
@jfacorro you mean `elvis_core 0.4.3`? This release still has that problem.

**Comment by jfacorro** [comment]
@hauleth Yes, sorry it is the current `master` but I was about to cut a new release and then didn't. The next 0.5.0 release will include the fix.

**Comment by jfacorro** [comment]
@hauleth There is now a new `0.5.0` release for `elvis_core`. We will shortly bump it in elvis.
