### ISSUE TITLE
Add ignore option for all existing rules

### ISSUE THREAD

**Issue by tothlac** [inaka/elvis#507]
It would be good to have this option for all existing rules since in our case we have some generated code. Even if the code is not generated, in some cases I want to add some exceptions. Would it be possible to add ignore option to all rules?

**Comment by elbrujohalcon** [comment]
Yeah, I think it's a good idea to have an `ignored` option as a generic one for all rules.

**Comment by jfacorro** [comment]
Me too! It should be relatively simple to refactor the code to handle ignores in a single place or at least in few places.

**Comment by paulo-ferraz-oliveira** [comment]
I'm going to give this a go. I'm going to start with name `ignore` (not `ignored`) since it's widespread already.
I'd like to implement this option for all rules with the following syntax:
```erlang
#{ ignore => [module() | {module(), atom()} | {module(), atom(), arity()}]}
```

**Comment by paulo-ferraz-oliveira** [comment]
I'd also like `ignore_functions` to go away (it's in `max_function_length`) since it'll be a duplicate. I mean, we can keep it for backwards compatibility, but I'm not keen on it.

**Comment by elbrujohalcon** [comment]
Remove it!

**Comment by paulo-ferraz-oliveira** [comment]
Funny enough (and for my own guidance and remembrance) the following don't parse the code tree:
* line_length,
* no_spaces,
* no_tabs,
* no_trailing_whitespace.
