### ISSUE TITLE
The way globs in elvis.config are interpreted generates duplicated analysis of files

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#508]
Even after inaka/elvis_core#111, we still have certain conditions in which we analyze some files twice.
To replicate the issue, build a project with the following subfolders:

* src
  - m1.erl
  - sub1
    * m2.erl
    * sub3
      - m3.erl

You can try with the following values for `dirs`:

* `["src/**"]`: that won't analyze `m1.erl`.
* `["src", "src/**"]`: that will analyze each module twice.
* `["src", "src/*", "src/*/*"]`: that will analyze `m1.erl` once, `m2.erl` twice and `m3.erl` three times.

**Comment by paulo-ferraz-oliveira** [comment]
Related to https://github.com/inaka/elvis_core/pull/124/commits/54c090e47300537465f4b2a91cdfa155dfd4848a.

**Comment by elbrujohalcon** [comment]
Fixed by inaka/elvis_core#124

**Comment by paulo-ferraz-oliveira** [comment]
> Fixed by [inaka/elvis_core#124](https://github.com/inaka/elvis_core/pull/124)

Nice. Shall we close it?
