### ISSUE TITLE
New Rule: atom_naming_convention

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis#516]
We some [naming convention rules](https://github.com/inaka/elvis_core/wiki/Rules#module-naming-convention) that deal with particular uses for atoms. It would be a good idea to create a more general rule that deals with *all* atoms at once.

Ref: WhatsApp/erlfmt#91

**Comment by paulo-ferraz-oliveira** [comment]
Linked to https://github.com/inaka/elvis_core/pull/132.

**Comment by paulo-ferraz-oliveira** [comment]
Reminder for future me: if this gets approved, you, @paulo-ferraz-oliveira, should update the Wiki.
