### ISSUE TITLE
Release request for `elvis_core`

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis#520]
As to include https://github.com/inaka/elvis_core/pull/122. Thanks.

**Comment by jfacorro** [comment]
New elvis_core 0.6.1 release is now available.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks. Is it possible to publish it to Hex also? It's the source `rebar3_lint` uses.

**Comment by jfacorro** [comment]
It is now published.
