### ISSUE TITLE
Wiki and/or code issues

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis#523]
1. `elvis_style:no_spaces/3` isn't documented as a rule. Is it a rule? The warning text is `Line ~p has a spaces at column ~p.`.
2. [this will probably spawn code] should we add `gen_statem` to "State Record and Type"?
3. both `no_seqbind` and `no_useless_seqbind` are rules that aren't specified in the Wiki. Should they be?

**Comment by paulo-ferraz-oliveira** [comment]
I also made a few changes to the Wiki: https://github.com/inaka/elvis_core/wiki/Rules/_history.

https://github.com/inaka/elvis_core/wiki/Rules/_compare/8f3079acfbea2eba8026beeaff6a2eaf0c6604b7...1ba2c797fc901ea656d8dcc63b5e153608835307 was actually a documentation bug.

And so was https://github.com/inaka/elvis_core/wiki/Rules/_compare/1ba2c797fc901ea656d8dcc63b5e153608835307...9ca00948411c15156b9c0f91c99a6fc7e44d796c.

And so was https://github.com/inaka/elvis_core/wiki/Rules/_compare/7bbff5023da11466ec6698e9757f96ec9dcc4364...c327905514a351508aae0e50538ee90475756ada.

**Comment by elbrujohalcon** [comment]
WOAH! Thank you, @paulo-ferraz-oliveira !!
To answer your questions…
1. Yes. It's a rule that's not part of the `erl_files` ruleset.
2. Yes, and yes… it requires a tiny code change.
3. Yes. They're rules that are not part of `erl_files`. As a matter of fact, since I don't think anybody is using them, I would just remove them.

**Comment by elbrujohalcon** [comment]
I don't remember who hated https://github.com/lpgauth/seqbind so thoroughly… but there must be an easier way to prevent its usage than using an elvis rule.

**Comment by paulo-ferraz-oliveira** [comment]
This: https://github.com/inaka/elvis_core/wiki/Rules/_compare/9dd797cf379827c2ecfc0fca571aed0f63427aff...fc4193a8db6ba54dd133d0ba2c7ae12b8e9fed77

**Comment by paulo-ferraz-oliveira** [comment]
> WOAH! Thank you, @paulo-ferraz-oliveira !!
> To answer your questions…
> 
> 1. Yes. It's a rule that's not part of the `erl_files` ruleset.
> 2. Yes, and yes… it requires a tiny code change.
> 3. Yes. They're rules that are not part of `erl_files`. As a matter of fact, since I don't think anybody is using them, I would just remove them.

1. Got it.
2. https://github.com/inaka/elvis_core/pull/128
3. https://github.com/inaka/elvis_core/pull/129

**Comment by elbrujohalcon** [comment]
> This: https://github.com/inaka/elvis_core/wiki/Rules/_compare/9dd797cf379827c2ecfc0fca571aed0f63427aff...fc4193a8db6ba54dd133d0ba2c7ae12b8e9fed77

Beautiful 🤩

**Comment by elbrujohalcon** [comment]
I think this is done.
