### ISSUE TITLE
Use of defaults in code

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis#525]
Due to the fact that the defaults in `elvis_rulesets.erl` and `elvis_style.erl` aren't always the same, the following might happen.

My `elvis.config` file has `{elvis_style, line_length, #{}}`. If I look at the Wiki, I might (wrongly assume the default is 100). The default being applied, in this case, isn't coming from the _rulesets_ but from the _style_, since the option map is present but the key isn't, which means `maps:get(limit, RuleConfig, 80)` evaluates to 80, not 100 (as expected).

Do you think it's best to:
1. leave this matter alone (it's fine as it is),
2. the defaults should be removed from the rulesets and only exist in the style (the rulesets would just include the rules themselves, not the options),
3. the defaults should be e.g. exposed in rulesets and then imported in style as, for example,
```erlang
% rulesets.erl
...
-export([default_line_length_limit/0]).
-define(DEFAULT_LINE_LENGTH_LIMIT, 100).
...
default_line_length_limit() -> ?DEFAULT_LINE_LENGTH_LIMIT.
...

% style.erl
...
line_length(_Config, Target, RuleConfig) ->
    Limit = maps:get(limit, RuleConfig, elvis_rulesets:default_line_length_limit()),
    ...
```
?

**Comment by elbrujohalcon** [comment]
Your concern is *very* valid.
I would personally strongly prefer your option #2, but I would be fine with #3, as long as you don't use macros and instead return the default value directly in the functions… Even more, I would do it this way:

```erlang
-spec default(module(), atom()) -> term().
default(line_length, limit) -> 100;
default(line_length, skip_comments) -> false;
…
```

**Comment by paulo-ferraz-oliveira** [comment]
Thanks, @elbrujohalcon. I think I'll go with a mix of both. A function that allows for an easier to maintain `elvis_rulesets` and a function with the defaults, so that `elvis_rule` can be easily maintained to. Both will read from the same _source_.

**Comment by paulo-ferraz-oliveira** [comment]
Something like
```erlang
-spec default(module(), function(), Option :: atom()) -> DefaultValue :: term().
default(elvis_style, line_length, limit) -> 100;
default(elvis_style, line_length, skip_comments) -> false.

-spec default(module(), function()) -> DefaultOption :: term().
default(elvis_style = M, line_length = F) -> #{limit => default(M, F, limit),
                                               skip_comments => default(M, F, limit)}.
```
, perhaps?

**Comment by paulo-ferraz-oliveira** [comment]
```erlang
maps:get(skip_comments, RuleConfig, false)
```
would become a more generic
```erlang
get_option(M, F, Option, RuleConfig) ->
    maps:get(Option, RuleConfig, default(M, F, Option)).
```
or is this _too_ abstract?

**Comment by paulo-ferraz-oliveira** [comment]
The way I'm looking at this now, which thus implied changes to two test cases, is that:
* if a rule map is `#{}` it doesn't mean "apply no options", since for that we can use `disabled`,
* thus, it actually means "I have no defined options, use the defaults".

**Comment by elbrujohalcon** [comment]
I don't really like having 2 `default` functions… Someday someone will add a literal value to a map `default/1` without using `default/3` and we'll then have a mix of places to put the defaults.
I would personally choose to only have `default/1` which returns both the maps with the default list of options and the defaults for those options… all written down in just one place.

**Comment by elbrujohalcon** [comment]
> The way I'm looking at this now, which thus implied changes to two test cases, is that:
> 
> * if a rule map is `#{}` it doesn't mean "apply no options", since for that we can use `disabled`,
> * thus, it actually means "I have no defined options, use the defaults".

I like this but it has to be properly documented.

**Comment by paulo-ferraz-oliveira** [comment]
> > The way I'm looking at this now, which thus implied changes to two test cases, is that:
> > 
> > * if a rule map is `#{}` it doesn't mean "apply no options", since for that we can use `disabled`,
> > * thus, it actually means "I have no defined options, use the defaults".
> 
> I like this but it has to be properly documented.

Where should it be documented?

**Comment by paulo-ferraz-oliveira** [comment]
> I don't really like having 2 `default` functions… Someday someone will add a literal value to a map `default/1` without using `default/3` and we'll then have a mix of places to put the defaults.
> I would personally choose to only have `default/1` which returns both the maps with the default list of options and the defaults for those options… all written down in just one place.

Sure, will do. It's an extra `maps:get` I think, but it should be performance-degrading in a significant way.

**Comment by elbrujohalcon** [comment]
> Sure, will do. It's an extra `maps:get` I think, but it should be performance-degrading in a significant way.

It shouldn't be performance degrading.

> Where should it be documented?

Probably [here](https://github.com/inaka/elvis_core/wiki/Rules#disabling-rules).

**Comment by paulo-ferraz-oliveira** [comment]
Should this be enough: 
> Note: using #{}, as an option map, will mean that defaults apply, i.e. it's not the same as disable
?

**Comment by elbrujohalcon** [comment]
Yeah!

**Comment by paulo-ferraz-oliveira** [comment]
> Yeah!

Done!
