### ISSUE TITLE
Document @since in the Rules' Wiki

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis#528]
At least for the latest versions available, in https://github.com/inaka/elvis_core/wiki/Rules. Kind of like `@since 0.7.0`.

Try to find a way to properly document the past for the other rules.

@elbrujohalcon, should we get rid of "Old format" in the Wiki? We can probably create a section to help developers migrate, but I think the semantics used (these days, using maps) is pretty self-explanatory.

**Comment by elbrujohalcon** [comment]
Yeah… the old format is clearly not used anymore anywhere… We could remove it from everywhere.

**Comment by elbrujohalcon** [comment]
And `@since` seems like a really nice thing, but retrofitting it to account for all rules… I think it would be too much work for no gain. We can start with `@since 0.7.0` for all rules.

**Comment by paulo-ferraz-oliveira** [comment]
> Yeah… the old format is clearly not used anymore anywhere… We could remove it from everywhere.

Done. There's `old_configuration_format` (which is "by default") so it shouldn't be hard for consumers to know there's something wrong.

**Comment by paulo-ferraz-oliveira** [comment]
As for `since` I went back to 0.4.0 (I just compared tags, in Git, so it was easy) and now we have it: https://github.com/inaka/elvis_core/wiki/Rules/_compare/7c99460d686073000d98b968ecb89cf507ba9359...fb84866eed10a4691cdd280aeb6def100a70f1a1.
