### ISSUE TITLE
New Rule: Consistency in andalso/orelse v. ;/, in guards

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis#538]
I tend to prefer explicit values `andalso`/`orelse` to their equivalent `;`/`,`, but can understand other's reasons for not doing this and keep consistency when I edit "foreign" modules.

In any case, favoring consistency, I also think that you should choose one style over the other in a given project. Let's make this configurable. And choose a default.

Ideas for default values? Ideas for rule name?

**Comment by jfacorro** [comment]
One comment I have regarding this is that `andalso`/`orelse` can be combined in ways `,`/`;` can't through the use of parenthesis. I'm not sure if enforcing the usage of a single style is limiting the expressions you can use and might need.

**Comment by elbrujohalcon** [comment]
Also... Since elvis analyzes files individually, the rule can't be "always use the same style". It must be "don't use $this and $that in guards".

I'm not too fond of this rule. But I am not 100% against it either.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, probably a dumb idea. Thanks for your thoughts.
