### ISSUE TITLE
New Rule: avoid high number of export_types

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis#539]
e.g. like `god_module`, but for `-export_type`.

Ideas?

**Comment by elbrujohalcon** [comment]
Is that even an issue anywhere?

I mean… people not defining types… I've seen *a lot*.
People defining too many types… I have yet to meet the first one of them.

**Comment by paulo-ferraz-oliveira** [comment]
I didn't come up with this; I saw it in production code. 😄 If it's not an issue, sure, it's not an issue.

**Comment by elbrujohalcon** [comment]
And now I want to see that code!!!

**Comment by paulo-ferraz-oliveira** [comment]
Oh, it's not shared online 😞. But I can tell you this: it's not a _god_ module, but it has more than 20 types 😄. When I suggested the idea, it would be for a number like that: at least 20 types. No worries, though; we'll get there. There's so much more interesting stuff to implement and fix, like _that_ `ignore` that's been itching.
