### ISSUE TITLE
Move from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis#555]
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

We should probably do the same for `elvis_core` if this proposal is accepted.

**Comment by jfacorro** [comment]
I didn't know about Travis CI being no longer useful. 😱 

I would welcome a PR for using Github actions. I don't think it is required to add it to master first, my experience is that the changes done in a branch will trigger the actions if they are enabled in the repo. I will double check this though.

**Comment by paulo-ferraz-oliveira** [comment]
You **don't need** to add it to `master`, but it'll only get triggered/available after merge to `master`, right?

> if they are enabled in the repo

Which they aren't, in `elvis`' case, are they?

**Comment by paulo-ferraz-oliveira** [comment]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing: "which allows around 1000 minutes in a Linux environment."

If I read https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions properly we're talking double the minutes on GitHub.com. I don't know where to get the actual consumption data, though.

**Comment by paulo-ferraz-oliveira** [comment]
You can probably check consumption here: https://github.com/organizations/inaka/settings/billing.

**Comment by paulo-ferraz-oliveira** [comment]
This was closed the moment #558 was too.
