### ISSUE TITLE
Try to have a GitHub Action for elvis

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis#557]
Or at least make it available in the same scope as `rebar3`, e.g. [here](https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/erlang.sh).

**Comment by paulo-ferraz-oliveira** [comment]
Tentatively assigning this to me. No promises, though. If you, the reader, want to tackle it, you're welcome. Pull requests are accepted.

**Comment by elbrujohalcon** [comment]
It seems like there was an error: https://github.com/inaka/elvis/actions/runs/414895885/workflow

**Comment by paulo-ferraz-oliveira** [comment]
I'll fix it. I knew I should've linted it.

**Comment by paulo-ferraz-oliveira** [comment]
I guess `rebar3_lint` does what this action would provide, so I'm closing the issue, for the moment.
