### ISSUE TITLE
Release in sync with elvis_core

### ISSUE THREAD

**Issue by andrei-mihaila** [inaka/elvis#571]
Hi,

It would be nice if this tool could benefit from the latest Elvis core.  Especially for those who use it inside erlang.mk projects, with the dedicated plugin.
Is there any reason (breaking API?) for not releasing this in sync with https://github.com/inaka/elvis_core?

Thanks!

**Comment by elbrujohalcon** [comment]
There is no particular reason, @andrei-mihaila … other than us (the maintainers) not using this as much as we use `rebar3_lint` ;)

**Comment by elbrujohalcon** [comment]
Done!
* https://github.com/inaka/elvis/releases/tag/3.0.1
* https://hex.pm/packages/elvis/3.0.1
