### ISSUE TITLE
Cannot install elvis

### ISSUE THREAD

**Issue by PhysicistProgs** [inaka/elvis#586]
I read instruction and expected that after `git clone` and `rebar3 compile` elvis is added to bin and can be used with `elvis rock` in any place in system. Am I wrong? 

After `git clone` -> `cd elvis` -> `rebar3 compile` elvis is not available to use in system. 
It can be used only if I call `rebar3 escriptize` and add generated escript to PATH manually.  

System: Ubuntu 22.04.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, the README is probably misleading. To use the application, you have to `git clone` it, `rebar escriptize` it, and put the generated binary in your system PATH. (this is also mentioned, but below section "Installation")

**Comment by paulo-ferraz-oliveira** [comment]
I'm gonna pull request to tweak the README so stuff's made clearer. For the time being I'm closing this issue as you've found the solution yourself and I just confirmed it 😄
